language: java
jdk:
- oraclejdk8
after_success:
- "./gradlew cobertura coveralls"
notifications:
  slack:
    secure: nJlIJNJxQMN0FP3lpU4VrDVO+7IjM5tnHIxIv6UC6yJqT9CxgW0WfNrBkwUj7GJeiAqENo9IlVXoSpSHDXIuul5dGrynkGGJ0tEhltUs0OHMlZEhDFo0InhdjfM9KYBR/v3wM9gOLh4bTiDQuTJNXehJKNV4G5E2iom9lo/avWRW1o0H4KybTRajKg1HNJ6gADnZcHRwGEFNmah10aH9OkD/GjeD6cThFNVuxxQfFMfKAvamq9zRTs4aHYxI0P671/cOjHX0EBhItkksHyZaK+6zW6Wxc9uCbZqCvQWcXI+tg92jaQWNCII2DikOn0rCduiicH0JkpSsaqK1NUReFjluoX9HMTtC58pcEDtPg7uSgYpAFhskRoiHCQAjVNN5vSg2uPHL5vy79+KZg3s5JBxMA1BFhqmclSSinqAa552FiL/ubv3bgeAu3iSjc6Z2PpkfKFaRzjMxXpOi+f5vmHO+bPRLe57Tj8QTBNPQrrRDFVXdrgbIsarrHktJLDyHFttzSNPjPYxsG4lnS4xri58UUk1b/ByIzzs/L4RMAbB/hHqKqH3I1NNlIrUoM6NOvYqyxexm6kkBldtkGr2bP8NtafXpyIRmQJP5aZ69AWZHJlMaHdrwuwYLWkMdD+utjU9Ti7kbEvGNrXCKaEMC7gUC1jZQZr2zM1HiMm1E8WA=
